apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: node-hello-tanzu
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: node-hello-tanzu
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/vmjpsa/node-hello-tanzu
      ref:
        branch: main